sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install

script:
  - vendor/bin/phing startup phpunitfast phpcs-console php-cs-fixer-dryrun
